const languages = ["en", "zh", "ja", "ko", "es", "fr", "de", "pt", "ru", "ar"];
const translations = {
  en: ["Password tools", "Tools / Symmetric encryption", "AES-GCM encrypts and authenticates a message with one secret key. This page derives that key from your password and runs entirely in your browser.", "Encrypt", "Decrypt", "Password", "Message", "Encrypt message", "Encrypted text", "Decrypt message", "Result", "Copy", "Message encrypted.", "Message decrypted.", "Wrong password or damaged encrypted text.", "Copied."],
  zh: ["密码工具", "工具 / 对称加密", "AES-GCM 使用同一个密钥加密并验证消息。本页面从密码生成密钥，所有操作都只在浏览器中完成。", "加密", "解密", "密码", "消息", "加密消息", "加密文本", "解密消息", "结果", "复制", "消息已加密。", "消息已解密。", "密码错误或加密文本已损坏。", "已复制。"],
  ja: ["パスワードツール", "ツール / 共通鍵暗号", "AES-GCMは1つの秘密鍵でメッセージを暗号化し認証します。鍵はパスワードからブラウザ内で生成されます。", "暗号化", "復号", "パスワード", "メッセージ", "暗号化する", "暗号化テキスト", "復号する", "結果", "コピー", "暗号化しました。", "復号しました。", "パスワードが違うかデータが破損しています。", "コピーしました。"],
  ko: ["비밀번호 도구", "도구 / 대칭 암호화", "AES-GCM은 하나의 비밀 키로 메시지를 암호화하고 인증합니다. 키는 브라우저에서 비밀번호로부터 생성됩니다.", "암호화", "복호화", "비밀번호", "메시지", "메시지 암호화", "암호문", "메시지 복호화", "결과", "복사", "암호화했습니다.", "복호화했습니다.", "비밀번호가 틀렸거나 암호문이 손상되었습니다.", "복사했습니다."],
  es: ["Herramientas de contraseña", "Herramientas / Cifrado simétrico", "AES-GCM cifra y autentica un mensaje con una clave secreta. La clave se deriva de tu contraseña dentro del navegador.", "Cifrar", "Descifrar", "Contraseña", "Mensaje", "Cifrar mensaje", "Texto cifrado", "Descifrar mensaje", "Resultado", "Copiar", "Mensaje cifrado.", "Mensaje descifrado.", "Contraseña incorrecta o texto dañado.", "Copiado."],
  fr: ["Outils de mot de passe", "Outils / Chiffrement symétrique", "AES-GCM chiffre et authentifie un message avec une clé secrète dérivée du mot de passe dans votre navigateur.", "Chiffrer", "Déchiffrer", "Mot de passe", "Message", "Chiffrer le message", "Texte chiffré", "Déchiffrer le message", "Résultat", "Copier", "Message chiffré.", "Message déchiffré.", "Mot de passe incorrect ou texte endommagé.", "Copié."],
  de: ["Passwortwerkzeuge", "Werkzeuge / Symmetrische Verschlüsselung", "AES-GCM verschlüsselt und authentifiziert mit einem geheimen Schlüssel, der im Browser aus dem Passwort abgeleitet wird.", "Verschlüsseln", "Entschlüsseln", "Passwort", "Nachricht", "Nachricht verschlüsseln", "Verschlüsselter Text", "Nachricht entschlüsseln", "Ergebnis", "Kopieren", "Nachricht verschlüsselt.", "Nachricht entschlüsselt.", "Falsches Passwort oder beschädigter Text.", "Kopiert."],
  pt: ["Ferramentas de senha", "Ferramentas / Criptografia simétrica", "AES-GCM cifra e autentica com uma chave secreta derivada da senha dentro do navegador.", "Criptografar", "Descriptografar", "Senha", "Mensagem", "Criptografar mensagem", "Texto criptografado", "Descriptografar mensagem", "Resultado", "Copiar", "Mensagem criptografada.", "Mensagem descriptografada.", "Senha incorreta ou texto danificado.", "Copiado."],
  ru: ["Инструменты паролей", "Инструменты / Симметричное шифрование", "AES-GCM шифрует и проверяет сообщение секретным ключом, созданным из пароля в браузере.", "Зашифровать", "Расшифровать", "Пароль", "Сообщение", "Зашифровать сообщение", "Зашифрованный текст", "Расшифровать сообщение", "Результат", "Копировать", "Сообщение зашифровано.", "Сообщение расшифровано.", "Неверный пароль или повреждённый текст.", "Скопировано."],
  ar: ["أدوات كلمات المرور", "أدوات / تشفير متماثل", "يشفر AES-GCM الرسالة ويتحقق منها بمفتاح سري مشتق من كلمة المرور داخل المتصفح.", "تشفير", "فك التشفير", "كلمة المرور", "الرسالة", "تشفير الرسالة", "النص المشفر", "فك تشفير الرسالة", "النتيجة", "نسخ", "تم تشفير الرسالة.", "تم فك التشفير.", "كلمة المرور غير صحيحة أو النص تالف.", "تم النسخ."]
};
const keys = ["passwordTools", "eyebrow", "intro", "encrypt", "decrypt", "password", "message", "encryptButton", "encrypted", "decryptButton", "result", "copy", "encryptedOk", "decryptedOk", "failed", "copied"];
const encoder = new TextEncoder();
const decoder = new TextDecoder();
const status = document.querySelector("#status");
const result = document.querySelector("#result-text");
function lang() { const value = localStorage.getItem("muye-lang") || "en"; return languages.includes(value) ? value : "en"; }
function t(key) { return translations[lang()][keys.indexOf(key)] || translations.en[keys.indexOf(key)] || key; }
function renderLanguage() { document.documentElement.lang = lang(); document.documentElement.dir = lang() === "ar" ? "rtl" : "ltr"; document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = t(node.dataset.i18n); }); document.querySelector("#language").textContent = lang() === "zh" ? "中A" : "A中"; }
function toBase64(bytes) { let value = ""; for (const byte of bytes) value += String.fromCharCode(byte); return btoa(value); }
function fromBase64(value) { const binary = atob(value); return Uint8Array.from(binary, (char) => char.charCodeAt(0)); }
async function keyFromPassword(password, salt) { const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt, iterations: 210000 }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
document.querySelector("#encrypt-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const key = await keyFromPassword(document.querySelector("#encrypt-password").value, salt); const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, encoder.encode(document.querySelector("#plain-text").value))); result.value = `aes_gcm$210000$${toBase64(salt)}$${toBase64(iv)}$${toBase64(cipher)}`; document.querySelector("#encrypted-text").value = result.value; status.className = "codec-status is-good"; status.textContent = t("encryptedOk"); } catch { status.className = "codec-status is-bad"; status.textContent = t("failed"); } });
document.querySelector("#decrypt-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const parts = document.querySelector("#encrypted-text").value.trim().split("$"); if (parts.length !== 5 || parts[0] !== "aes_gcm" || parts[1] !== "210000") throw new Error(); const key = await keyFromPassword(document.querySelector("#decrypt-password").value, fromBase64(parts[2])); const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(parts[3]) }, key, fromBase64(parts[4])); result.value = decoder.decode(plain); status.className = "codec-status is-good"; status.textContent = t("decryptedOk"); } catch { status.className = "codec-status is-bad"; status.textContent = t("failed"); } });
document.querySelector("#copy-result").addEventListener("click", async () => { if (!result.value) return; await navigator.clipboard.writeText(result.value); status.textContent = t("copied"); });
document.querySelector("#language").addEventListener("click", () => { const current = lang(); const next = languages[(languages.indexOf(current) + 1) % languages.length]; localStorage.setItem("muye-lang", next); window.dispatchEvent(new CustomEvent("muye-language-change", { detail: { lang: next } })); renderLanguage(); });
window.addEventListener("muye-language-change", renderLanguage);
renderLanguage();
