const text = {
  en: { eyebrow: "Muye mail", adminLogin: "Mailbox admin", adminLoginCopy: "Enter the admin password to view all mailboxes and messages.", password: "Password", openAdmin: "Open admin", admin: "Admin", allMailboxes: "All mailboxes", mailboxes: "Mailboxes", messages: "Messages", refresh: "Refresh", signOut: "Sign out", chooseMailbox: "Choose a mailbox.", noMailboxes: "No mailboxes yet.", noMessages: "No messages in this mailbox.", wrongPassword: "Admin password is incorrect." },
  zh: { eyebrow: "Muye 邮箱", adminLogin: "邮箱管理", adminLoginCopy: "输入管理员密码查看所有邮箱和邮件。", password: "密码", openAdmin: "打开管理", admin: "管理", allMailboxes: "所有邮箱", mailboxes: "邮箱", messages: "邮件", refresh: "刷新", signOut: "退出", chooseMailbox: "选择一个邮箱。", noMailboxes: "还没有邮箱。", noMessages: "这个邮箱没有邮件。", wrongPassword: "管理员密码不正确。" },
  ja: { eyebrow: "Muye メール", adminLogin: "メール管理", adminLoginCopy: "管理者パスワードを入力してすべてのメールボックスとメッセージを表示します。", password: "パスワード", openAdmin: "管理を開く", admin: "管理", allMailboxes: "すべてのメールボックス", mailboxes: "メールボックス", messages: "メッセージ", refresh: "更新", signOut: "ログアウト", chooseMailbox: "メールボックスを選択してください。", noMailboxes: "メールボックスはまだありません。", noMessages: "このメールボックスにメッセージはありません。", wrongPassword: "管理者パスワードが正しくありません。" },
  ko: { eyebrow: "Muye 메일", adminLogin: "메일함 관리자", adminLoginCopy: "관리자 비밀번호를 입력하면 모든 메일함과 메시지를 볼 수 있습니다.", password: "비밀번호", openAdmin: "관리자 열기", admin: "관리", allMailboxes: "모든 메일함", mailboxes: "메일함", messages: "메시지", refresh: "새로고침", signOut: "로그아웃", chooseMailbox: "메일함을 선택하세요.", noMailboxes: "메일함이 아직 없습니다.", noMessages: "이 메일함에는 메시지가 없습니다.", wrongPassword: "관리자 비밀번호가 올바르지 않습니다." },
  es: { eyebrow: "Correo Muye", adminLogin: "Administración del buzón", adminLoginCopy: "Escribe la contraseña de administrador para ver todos los buzones y mensajes.", password: "Contraseña", openAdmin: "Abrir administración", admin: "Administración", allMailboxes: "Todos los buzones", mailboxes: "Buzones", messages: "Mensajes", refresh: "Actualizar", signOut: "Salir", chooseMailbox: "Elige un buzón.", noMailboxes: "Aún no hay buzones.", noMessages: "No hay mensajes en este buzón.", wrongPassword: "La contraseña de administrador es incorrecta." },
  fr: { eyebrow: "Courrier Muye", adminLogin: "Administration de la boîte", adminLoginCopy: "Saisissez le mot de passe administrateur pour voir toutes les boîtes et les messages.", password: "Mot de passe", openAdmin: "Ouvrir l’administration", admin: "Administration", allMailboxes: "Toutes les boîtes", mailboxes: "Boîtes", messages: "Messages", refresh: "Actualiser", signOut: "Déconnexion", chooseMailbox: "Choisissez une boîte.", noMailboxes: "Aucune boîte pour le moment.", noMessages: "Aucun message dans cette boîte.", wrongPassword: "Le mot de passe administrateur est incorrect." },
  de: { eyebrow: "Muye-Mail", adminLogin: "Postfachverwaltung", adminLoginCopy: "Gib das Admin-Passwort ein, um alle Postfächer und Nachrichten zu sehen.", password: "Passwort", openAdmin: "Admin öffnen", admin: "Admin", allMailboxes: "Alle Postfächer", mailboxes: "Postfächer", messages: "Nachrichten", refresh: "Aktualisieren", signOut: "Abmelden", chooseMailbox: "Wähle ein Postfach.", noMailboxes: "Noch keine Postfächer.", noMessages: "Keine Nachrichten in diesem Postfach.", wrongPassword: "Das Admin-Passwort ist falsch." },
  pt: { eyebrow: "Email Muye", adminLogin: "Administração da caixa", adminLoginCopy: "Digite a senha de administrador para ver todas as caixas e mensagens.", password: "Senha", openAdmin: "Abrir administração", admin: "Admin", allMailboxes: "Todas as caixas", mailboxes: "Caixas", messages: "Mensagens", refresh: "Atualizar", signOut: "Sair", chooseMailbox: "Escolha uma caixa.", noMailboxes: "Ainda não há caixas.", noMessages: "Não há mensagens nesta caixa.", wrongPassword: "A senha de administrador está incorreta." },
  ru: { eyebrow: "Почта Muye", adminLogin: "Администратор почты", adminLoginCopy: "Введите пароль администратора, чтобы просмотреть все ящики и сообщения.", password: "Пароль", openAdmin: "Открыть админку", admin: "Админ", allMailboxes: "Все почтовые ящики", mailboxes: "Ящики", messages: "Сообщения", refresh: "Обновить", signOut: "Выйти", chooseMailbox: "Выберите ящик.", noMailboxes: "Ящиков пока нет.", noMessages: "В этом ящике нет сообщений.", wrongPassword: "Пароль администратора неверен." },
  ar: { eyebrow: "بريد Muye", adminLogin: "إدارة البريد", adminLoginCopy: "أدخل كلمة مرور المسؤول لعرض جميع الصناديق والرسائل.", password: "كلمة المرور", openAdmin: "فتح الإدارة", admin: "المسؤول", allMailboxes: "كل الصناديق", mailboxes: "الصناديق", messages: "الرسائل", refresh: "تحديث", signOut: "خروج", chooseMailbox: "اختر صندوقًا.", noMailboxes: "لا توجد صناديق بعد.", noMessages: "لا توجد رسائل في هذا الصندوق.", wrongPassword: "كلمة مرور المسؤول غير صحيحة." },
};
const lang = () => text[localStorage.getItem("muye-lang") || "en"] ? (localStorage.getItem("muye-lang") || "en") : "en";
const t = (key) => text[lang()][key] || text.en[key] || key;
const escapeHtml = (value) => String(value || "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
const formatDate = (value) => new Date(`${value}Z`).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
const login = document.querySelector("#admin-login"); const dashboard = document.querySelector("#admin-dashboard"); const message = document.querySelector("#admin-login-message"); const mailboxList = document.querySelector("#mailbox-list"); const messageList = document.querySelector("#message-list"); const detail = document.querySelector("#message-detail");
function applyLanguage() { document.documentElement.lang = lang(); document.documentElement.dir = lang() === "ar" ? "rtl" : "ltr"; document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = t(node.dataset.i18n); }); }
async function api(url, options) { const response = await fetch(url, options); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(response.status === 401 ? t("wrongPassword") : result.error || t("wrongPassword")); return result; }
function renderMailboxes(mailboxes) { document.querySelector("#admin-summary").textContent = `${mailboxes.length} ${t("mailboxes").toLowerCase()}`; mailboxList.innerHTML = mailboxes.length ? mailboxes.map((item) => `<button class="message-item" data-mailbox="${escapeHtml(item.mailbox)}" type="button"><span class="message-meta"><span>${escapeHtml(item.mailbox)}</span><time>${formatDate(item.created_at)}</time></span><span class="message-subject">${Number(item.message_count || 0)} ${t("messages").toLowerCase()}</span></button>`).join("") : `<div class="empty-state">${t("noMailboxes")}</div>`; mailboxList.querySelectorAll("[data-mailbox]").forEach((button) => button.addEventListener("click", () => loadMessages(button.dataset.mailbox))); }
async function loadDashboard() { const result = await api("/api/admin-mailboxes"); renderMailboxes(result.mailboxes || []); }
async function loadMessages(mailbox) { const result = await api(`/api/admin-mailboxes?mailbox=${encodeURIComponent(mailbox)}`); document.querySelector("#message-title").textContent = `${t("messages")}: ${mailbox}`; const messages = result.messages || []; messageList.innerHTML = messages.length ? messages.map((item) => `<button class="message-item" data-message-id="${item.id}" type="button"><span class="message-meta"><span>${escapeHtml(item.direction)}</span><time>${formatDate(item.created_at)}</time></span><span class="message-subject">${escapeHtml(item.subject)}</span><span class="message-preview">${escapeHtml(item.sender)} → ${escapeHtml(item.recipient)}</span></button>`).join("") : `<div class="empty-state">${t("noMessages")}</div>`; detail.innerHTML = `<p class="empty-state">${t("chooseMailbox")}</p>`; messageList.querySelectorAll("[data-message-id]").forEach((button) => button.addEventListener("click", () => { const item = messages.find((entry) => String(entry.id) === button.dataset.messageId); if (item) detail.innerHTML = `<div class="message-detail-meta"><span>${escapeHtml(item.sender)} → ${escapeHtml(item.recipient)}</span><time>${formatDate(item.created_at)}</time></div><h3>${escapeHtml(item.subject)}</h3><pre>${escapeHtml(item.body)}</pre>`; })); }
async function openDashboard() { login.hidden = true; dashboard.hidden = false; await loadDashboard(); }
document.querySelector("#admin-login-form").addEventListener("submit", async (event) => { event.preventDefault(); message.textContent = ""; try { await api("/api/mailbox-admin-login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: new FormData(event.currentTarget).get("password") }) }); await openDashboard(); } catch (error) { message.textContent = error.message; message.classList.add("error"); } });
document.querySelector("#admin-refresh").addEventListener("click", loadDashboard); document.querySelector("#admin-logout").addEventListener("click", async () => { await fetch("/api/mailbox-admin-login", { method: "DELETE" }); dashboard.hidden = true; login.hidden = false; }); applyLanguage();
